<?php

namespace Database\Seeders;

use App\Models\Workout;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkoutSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['time' => '22', 'video' => 'videos/fullbody 1.mp4', 'title' => 'Bài tập toàn thân 1', 'description' => 'Đây là một trong những bài tập thể dục hỗ trợ đốt cháy mỡ thừa, đốt cháy calo mạnh mẽ và tăng nhịp tim, tăng cường sức chịu đựng của tim mạch rất hiệu quả. Đây là bài tập thể dục giảm mỡ khá được ưa chuộng cho cả nam lẫn nữ.', 'calo' => '303', 'image' => 'images/fullbody 1.jpeg', 'level' => '2',],
            ['time' => '21', 'video' => 'videos/fullbody 2.mp4', 'title' => 'Bài tập toàn thân 2', 'description' => 'Đây là bài tập tác động chủ yếu lên đôi bắp chân, bắp tay và vùng bụng, giúp đốt cháy mỡ thừa toàn thân rất hiệu quả.', 'calo' => '469', 'image' => 'images/fullbody 2.jpeg', 'level' => '1',],
            ['time' => '14', 'video' => 'videos/fullbody 3.mp4', 'title' => 'Bài tập toàn thân 3', 'description' => 'Các động tác tập luyện của bài tập này giúp đốt cháy lượng calo tương đối cao, hỗ trợ giảm mỡ toàn thân nhanh chóng.', 'calo' => '396', 'image' => 'images/fullbody 3.jpeg', 'level' => '2',],
            ['time' => '34', 'video' => 'videos/fullbody 4.mp4', 'title' => 'Bài tập toàn thân 4', 'description' => 'Bài tập này thuộc bài tập giảm mỡ thừa toàn thân khá đơn giản, phù hợp cho nhiều người tập luyện. ', 'calo' => '417', 'image' => 'images/fullbody 4.jpeg', 'level' => '3',],
            ['time' => '37', 'video' => 'videos/fullbody 5.mp4', 'title' => 'Bài tập toàn thân 5', 'description' => 'Đây được coi là bài tập rất đơn giản, không cần sử dụng nhiều động tác nên người tập không cần vận động nhiều nhưng khả năng đốt cháy mỡ thừa của nó lại cực kỳ tốt.', 'calo' => '317', 'image' => 'images/fullbody 5.jpeg', 'level' => '3',],
            ['time' => '9', 'video' => 'videos/fullbody 6.mp4', 'title' => 'Bài tập toàn thân 6', 'description' => 'Đây là bài tập cơ bản giúp đánh tan mỡ thừa vùng bụng rất hiệu quả. Không những vậy, bài tập này còn hỗ trợ tiêu hao calo, giúp giảm mỡ toàn thân rất nhanh chóng.', 'calo' => '292', 'image' => 'images/fullbody 6.jpeg', 'level' => '2',],
            ['time' => '15', 'video' => 'videos/yoga1.mp4', 'title' => 'Bài tập yoga 1', 'description' => 'Các tư thế yoga đứng giúp tăng cường sức mạnh, cải thiện khả năng giữ thăng bằng và sự linh hoạt cho đôi chân. Không những thế, tập luyện bài tập này cũng mang lại nhiều lợi ích cho các bộ phận khác trên cơ thể', 'calo' => '479', 'image' => 'images/yoga1.jpeg', 'level' => '3',],
            ['time' => '31', 'video' => 'videos/yoga2.mp4', 'title' => 'Bài tập yoga 2', 'description' => 'Thực hành các tư thế yoga trong bài tập này sẽ giúp cải thiện sức mạnh cốt lõi, săn chắc cơ bụng và cũng có thể giảm đau lưng', 'calo' => '104', 'image' => 'images/yoga2.jpeg', 'level' => '3',],
            ['time' => '6', 'video' => 'videos/yoga3.mp4', 'title' => 'Bài tập yoga 3', 'description' => 'Những tư thế này sẽ giúp tăng sức mạnh của lưng và khả năng vận động của cột sống', 'calo' => '145', 'image' => 'images/yoga3.jpeg', 'level' => '2',],
            ['time' => '21', 'video' => 'videos/yoga4.mp4', 'title' => 'Bài tập yoga 4', 'description' => 'Thực hiện các tư thế này có thể giúp ngăn ngừa đau lưng và cổ.', 'calo' => '395', 'image' => 'images/yoga4.jpeg', 'level' => '2',],
            ['time' => '11', 'video' => 'videos/yoga5.mp4', 'title' => 'Bài tập yoga 5', 'description' => 'Bài tập giúp giảm mỡ, tăng khả năng đàn hồi của cột sống, có tác dụng tập trung tại vị trí lưng và dưới thắt lưng', 'calo' => '409', 'image' => 'images/yoga5.jpeg', 'level' => '2',],
            ['time' => '21', 'video' => 'videos/tocdo1.mp4', 'title' => 'Bài tập tốc độ 1', 'description' => 'Đây là một bài tập toàn thân tuyệt vời giúp tăng cường mọi cơ bắp trên cơ thể bạn, giúp nâng cao sức mạnh và bùng nổ tốc độ.', 'calo' => '313', 'image' => 'images/tocdo1.jpeg', 'level' => '3',],
            ['time' => '9', 'video' => 'videos/tocdo2.mp4', 'title' => 'Bài tập tốc độ 2', 'description' => 'Đây là dạng bài tập rất tốt để rèn luyện cơ chân và cơ bắp, giúp bạn chạy nhanh hơn. Đây cũng là một trong những mẹo khởi động trước khi chạy nhanh để đạt hiệu quả cao hơn.', 'calo' => '261', 'image' => 'images/tocdo2.jpeg', 'level' => '2',],
            ['time' => '31', 'video' => 'videos/thiendinh1.mp4', 'title' => 'Bài tập thiền định 1', 'description' => 'Giúp bạn tập trung tư tưởng mọi nơi, mọi lúc.', 'calo' => '269', 'image' => 'images/thiendinh1.jpeg', 'level' => '3',],
            ['time' => '33', 'video' => 'videos/thiendinh2.mp4', 'title' => 'Bài tập thiền định 2', 'description' => 'Loại thiền này giúp nhận biết các cử động cơ bản nhất của quá trình đi bộ', 'calo' => '252', 'image' => 'images/thiendinh2.jpeg', 'level' => '3',],
            ['time' => '40', 'video' => 'videos/thiendinh3.mp4', 'title' => 'Bài tập thiền định 3', 'description' => 'Đây là một bài tập phục hồi năng lượng. Nó giúp xua đuổi những suy nghĩ xáo trộn', 'calo' => '359', 'image' => 'images/thiendinh3.jpeg', 'level' => '3',],
            ['time' => '5', 'video' => 'videos/thiendinh4.mp4', 'title' => 'Bài tập thiền định 4', 'description' => 'Giúp bạn ngủ ngon hơn. Là kỹ thuật thư giãn, nó có thể giúp tâm trí và cơ thể yên tĩnh trong khi tăng cường sự bình yên bên trong.', 'calo' => '269', 'image' => 'images/thiendinh4.jpeg', 'level' => '3',],
            ['time' => '12', 'video' => 'videos/khoidong1.mp4', 'title' => 'Bài tập khởi động 1', 'description' => 'Giúp làm nóng cơ mông và cơ gấp hông, cơ tứ đầu, cơ bụng, bắp chân và gân kheo.', 'calo' => '435', 'image' => 'images/khoidong1.webp', 'level' => '2',],
            ['time' => '6', 'video' => 'videos/khoidong2.mp4', 'title' => 'Bài tập khởi động 2', 'description' => 'Động tác này sẽ kích hoạt các cơ cốt lõi hỗ trợ cột sống của bạn để chuẩn bị cho quá trình tập luyện. ', 'calo' => '381', 'image' => 'images/khoidong2.webp', 'level' => '3',],
            ['time' => '6', 'video' => 'videos/khoidong3.mp4', 'title' => 'Bài tập khởi động 3', 'description' => 'Động tác khởi động căng cơ tích cực này cũng có thể giúp giảm đau nhức và căng cơ cổ. Tạo thách thức cột sống ngực và khả năng vận động của vai của bạn.', 'calo' => '146', 'image' => 'images/khoidong3.webp', 'level' => '2',],
            ['time' => '40', 'video' => 'videos/chan1.mp4', 'title' => 'Bài tập chân 1', 'description' => 'Sẽ tác động vào cơ đùi trước (Quad), Cơ đùi sau (Hamstrings), Mông (Glute) với mức độ khác nhau.', 'calo' => '362', 'image' => 'images/chan1.webp', 'level' => '1',],
            ['time' => '20', 'video' => 'videos/chan2.mp4', 'title' => 'Bài tập chân 2', 'description' => 'Giúp nam giới sở hữu bắp đùi to khỏe và giúp nữ giới giảm mỡ đùi nhanh chóng.', 'calo' => '425', 'image' => 'images/chan2.webp', 'level' => '2',],
            ['time' => '37', 'video' => 'videos/chan3.mp4', 'title' => 'Bài tập chân 3', 'description' => 'Đây là bài tập cơ chân hiệu quả có thể giúp bạn nhắm vào cơ bắp chân, cơ đùi và nhóm cơ phụ như cơ đùi sau, cơ mông.,', 'calo' => '367', 'image' => 'images/chan3.webp', 'level' => '2',],
            ['time' => '40', 'video' => 'videos/bung1.mp4', 'title' => 'Bài tập bụng 1', 'description' => 'Đây là bài tập cơ bụng đơn giản mà các bạn mới bắt đầu tập gym có thể dễ dàng làm được. Bài tập thích hợp với cả nam và nữ. Với động tác này, chỉ có cơ bụng tham gia vào quá trình nâng đỡ người lên, không có sự can thiệp của lực tay và vai.', 'calo' => '160', 'image' => 'images/bung1.webp', 'level' => '3',],
            ['time' => '22', 'video' => 'videos/bung2.mp4', 'title' => 'Bài tập bụng 2', 'description' => 'Tập trung chủ yếu vào vùng cơ bụng, phần cơ liên sườn và cả cơ ở tay. Động tác này sẽ giúp bạn đốt cháy phần calo dư thừa trong cơ thể nhiều hơn là việc tổng hợp các nhóm cơ cùng hoạt động.', 'calo' => '285', 'image' => 'images/bung2.webp', 'level' => '3',],
            ['time' => '6', 'video' => 'videos/bung3.mp4', 'title' => 'Bài tập bụng 3', 'description' => 'Tập luyện bài tập này giúp nâng cơ phần bụng. Cơ bụng sẽ trở nên săn chắc hơn trông thấy sau một thời gian tập luyện', 'calo' => '273', 'image' => 'images/bung3.webp', 'level' => '1',],
            ['time' => '39', 'video' => 'videos/bung4.mp4', 'title' => 'Bài tập bụng 4', 'description' => 'Đây là bài tập cơ bụng tại nhà giúp giảm mỡ, eo thon cơ bản nếu muốn có vóc dáng thon đẹp. Với bài tập này các cơ ở bụng sẽ tác động và giảm đi lượng mỡ tích tụ giúp cho vòng eo sexy hơn.', 'calo' => '202', 'image' => 'images/bung4.webp', 'level' => '2',],
            ['time' => '17', 'video' => 'videos/tay1.mp4', 'title' => 'Bài tập tay 1', 'description' => 'Động tác này có tác dụng làm căng cơ duỗi ở phía trên cẳng tay.', 'calo' => '477', 'image' => 'images/tay1.webp', 'level' => '2',],
            ['time' => '34', 'video' => 'videos/tay2.mp4', 'title' => 'Bài tập tay 2', 'description' => 'Là bài tập cơ tay hiệu quả nhất giúp tập trung tăng cường cơ tay trước của bạn.', 'calo' => '170', 'image' => 'images/tay2.webp', 'level' => '1',],
            ['time' => '17', 'video' => 'videos/tay3.mp4', 'title' => 'Bài tập tay 3', 'description' => 'Là bài tập quen thuộc giúp tăng cường sức mạnh cho phần thân trên, tác động hiệu quả đến nhiều cơ cùng một lúc, bao gồm cả cơ ngực, cơ tam đầu và cơ delta ở vai.', 'calo' => '293', 'image' => 'images/tay3.webp', 'level' => '3',],
            ['time' => '21', 'video' => 'videos/gym1.mp4', 'title' => 'Bài tập gym 1', 'description' => 'Khiến hai tay cần giữ lực toàn thân và di chuyển lên xuống, tác động mạnh lên cơ ngực, cơ tay sau và một phần cơ vai. Đây là một trong những bài tập gym tại nhà đơn giản nhất nhưng rất hiệu quả mà bạn nên áp dụng.', 'calo' => '109', 'image' => 'images/gym1.webp', 'level' => '2',],
            ['time' => '20', 'video' => 'videos/gym2.mp4', 'title' => 'Bài tập gym 2', 'description' => 'Bài tập này tác động hiệu quả lên cơ tay sau, cầu vai và một phần cơ ngực.', 'calo' => '166', 'image' => 'images/gym2.webp', 'level' => '1',],
            ['time' => '18', 'video' => 'videos/gym3.mp4', 'title' => 'Bài tập gym 3', 'description' => 'Bài tập gym này phù hợp với cả nam lẫn nữ, đặc biệt các bạn nữ không muốn phát triển cơ tay quá to và muốn vùng mông đùi săn chắc hơn. ', 'calo' => '104', 'image' => 'images/gym3.webp', 'level' => '3',],
            ['time' => '37', 'video' => 'videos/gym4.mp4', 'title' => 'Bài tập gym 4', 'description' => 'Sẽ tác động chủ yếu lên cơ mông, cơ đùi sau, giúp đốt cháy mỡ thừa và cơ thể săn chắc hơn.', 'calo' => '472', 'image' => 'images/gym4.webp', 'level' => '1',],
            ['time' => '28', 'video' => 'videos/gym5.mp4', 'title' => 'Bài tập gym 5', 'description' => 'Bài tập này đặc biệt tập trung vào vùng cơ bụng trên, giúp chúng trở nên săn chắc, không còn mỡ thừa.', 'calo' => '185', 'image' => 'images/gym5.webp', 'level' => '1',],
            ['time' => '16', 'video' => 'videos/dance1.mp4', 'title' => 'Bài tập nhảy 1', 'description' => 'Giúp làm nóng toàn thân và hỗ trợ máu lưu thông tốt hơn. Bài tập đòi hỏi sự phối hợp chân tay và đi liền với gập bụng nhanh giúp đốt mỡ thừa, lấy lại vóc dáng.', 'calo' => '346', 'image' => 'images/dance1.webp', 'level' => '1',],
            ['time' => '7', 'video' => 'videos/dance2.mp4', 'title' => 'Bài tập nhảy 2', 'description' => 'Đây là bài tập tác động trực tiếp vào phần hông và bụng dưới.', 'calo' => '141', 'image' => 'images/dance2.webp', 'level' => '3',],
            ['time' => '35', 'video' => 'videos/dance3.mp4', 'title' => 'Bài tập nhảy 3', 'description' => 'Bài tập này mang lại hiệu quả cực tốt không chỉ tập trung vào phần eo mà cả ở cánh tay và bụng đùi.', 'calo' => '266', 'image' => 'images/dance3.webp', 'level' => '1',],
            ['time' => '32', 'video' => 'videos/dance4.mp4', 'title' => 'Bài tập nhảy 4', 'description' => 'Bài tập giật cơ sẽ tác động vào phần bụng với cường độ mạnh để làm tan những lớp mỡ dư thừa cứng đầu và đốt cháy calo. Nhờ vậy quá trình giảm mỡ thừa sẽ diễn ra nhanh chóng', 'calo' => '194', 'image' => 'images/dance4.webp', 'level' => '1',],
            ['time' => '10', 'video' => 'videos/dance5.mp4', 'title' => 'Bài tập nhảy 5', 'description' => 'Khi tập luyện bài tập này làm giảm những lượng mỡ dư thừa ở vùng eo, hông mà ở bắp chân cũng được đốt cháy, cơ bắp săn chắc hơn.', 'calo' => '197', 'image' => 'images/dance5.webp', 'level' => '2',],
        ];
        foreach ($data as $each) {
            Workout::query()->create($each);
        }

        $workout_tags = [
            ["workout_id" => 1, "tag_id" => "12"],
            ["workout_id" => 1, "tag_id" => "10"],
            ["workout_id" => 1, "tag_id" => "9"],
            ["workout_id" => 1, "tag_id" => "11"],
            ["workout_id" => 1, "tag_id" => "20"],
            ["workout_id" => 1, "tag_id" => "21"],
            ["workout_id" => 2, "tag_id" => "12"],
            ["workout_id" => 2, "tag_id" => "10"],
            ["workout_id" => 2, "tag_id" => "9"],
            ["workout_id" => 2, "tag_id" => "11"],
            ["workout_id" => 2, "tag_id" => "20"],
            ["workout_id" => 3, "tag_id" => "12"],
            ["workout_id" => 3, "tag_id" => "10"],
            ["workout_id" => 3, "tag_id" => "9"],
            ["workout_id" => 3, "tag_id" => "11"],
            ["workout_id" => 3, "tag_id" => "23"],
            ["workout_id" => 3, "tag_id" => "22"],
            ["workout_id" => 4, "tag_id" => "12"],
            ["workout_id" => 4, "tag_id" => "10"],
            ["workout_id" => 4, "tag_id" => "9"],
            ["workout_id" => 4, "tag_id" => "11"],
            ["workout_id" => 4, "tag_id" => "20"],
            ["workout_id" => 4, "tag_id" => "21"],
            ["workout_id" => 5, "tag_id" => "12"],
            ["workout_id" => 5, "tag_id" => "10"],
            ["workout_id" => 5, "tag_id" => "9"],
            ["workout_id" => 5, "tag_id" => "11"],
            ["workout_id" => 5, "tag_id" => "20"],
            ["workout_id" => 5, "tag_id" => "21"],
            ["workout_id" => 6, "tag_id" => "12"],
            ["workout_id" => 6, "tag_id" => "10"],
            ["workout_id" => 6, "tag_id" => "9"],
            ["workout_id" => 6, "tag_id" => "11"],
            ["workout_id" => 6, "tag_id" => "21"],
            ["workout_id" => 7, "tag_id" => "13"],
            ["workout_id" => 7, "tag_id" => "9"],
            ["workout_id" => 7, "tag_id" => "10"],
            ["workout_id" => 7, "tag_id" => "11"],
            ["workout_id" => 7, "tag_id" => "20"],
            ["workout_id" => 8, "tag_id" => "13"],
            ["workout_id" => 8, "tag_id" => "9"],
            ["workout_id" => 8, "tag_id" => "10"],
            ["workout_id" => 8, "tag_id" => "11"],
            ["workout_id" => 8, "tag_id" => "20"],
            ["workout_id" => 9, "tag_id" => "13"],
            ["workout_id" => 9, "tag_id" => "11"],
            ["workout_id" => 9, "tag_id" => "20"],
            ["workout_id" => 10, "tag_id" => "13"],
            ["workout_id" => 10, "tag_id" => "9"],
            ["workout_id" => 10, "tag_id" => "10"],
            ["workout_id" => 10, "tag_id" => "11"],
            ["workout_id" => 10, "tag_id" => "20"],
            ["workout_id" => 11, "tag_id" => "13"],
            ["workout_id" => 11, "tag_id" => "9"],
            ["workout_id" => 11, "tag_id" => "11"],
            ["workout_id" => 11, "tag_id" => "20"],
            ["workout_id" => 12, "tag_id" => "15"],
            ["workout_id" => 12, "tag_id" => "11"],
            ["workout_id" => 12, "tag_id" => "20"],
            ["workout_id" => 13, "tag_id" => "15"],
            ["workout_id" => 13, "tag_id" => "11"],
            ["workout_id" => 13, "tag_id" => "9"],
            ["workout_id" => 13, "tag_id" => "10"],
            ["workout_id" => 13, "tag_id" => "20"],
            ["workout_id" => 14, "tag_id" => "19"],
            ["workout_id" => 14, "tag_id" => "20"],
            ["workout_id" => 14, "tag_id" => "21"],
            ["workout_id" => 14, "tag_id" => "9"],
            ["workout_id" => 15, "tag_id" => "19"],
            ["workout_id" => 15, "tag_id" => "21"],
            ["workout_id" => 15, "tag_id" => "9"],
            ["workout_id" => 15, "tag_id" => "10"],
            ["workout_id" => 15, "tag_id" => "11"],
            ["workout_id" => 16, "tag_id" => "19"],
            ["workout_id" => 16, "tag_id" => "20"],
            ["workout_id" => 16, "tag_id" => "9"],
            ["workout_id" => 16, "tag_id" => "10"],
            ["workout_id" => 17, "tag_id" => "19"],
            ["workout_id" => 17, "tag_id" => "20"],
            ["workout_id" => 17, "tag_id" => "21"],
            ["workout_id" => 17, "tag_id" => "9"],
            ["workout_id" => 18, "tag_id" => "16"],
            ["workout_id" => 18, "tag_id" => "9"],
            ["workout_id" => 18, "tag_id" => "10"],
            ["workout_id" => 18, "tag_id" => "11"],
            ["workout_id" => 18, "tag_id" => "20"],
            ["workout_id" => 19, "tag_id" => "16"],
            ["workout_id" => 19, "tag_id" => "9"],
            ["workout_id" => 19, "tag_id" => "10"],
            ["workout_id" => 19, "tag_id" => "11"],
            ["workout_id" => 19, "tag_id" => "21"],
            ["workout_id" => 20, "tag_id" => "16"],
            ["workout_id" => 20, "tag_id" => "9"],
            ["workout_id" => 20, "tag_id" => "10"],
            ["workout_id" => 20, "tag_id" => "11"],
            ["workout_id" => 20, "tag_id" => "22"],
            ["workout_id" => 21, "tag_id" => "11"],
            ["workout_id" => 21, "tag_id" => "9"],
            ["workout_id" => 21, "tag_id" => "10"],
            ["workout_id" => 21, "tag_id" => "20"],
            ["workout_id" => 22, "tag_id" => "11"],
            ["workout_id" => 22, "tag_id" => "9"],
            ["workout_id" => 22, "tag_id" => "10"],
            ["workout_id" => 22, "tag_id" => "23"],
            ["workout_id" => 23, "tag_id" => "11"],
            ["workout_id" => 23, "tag_id" => "9"],
            ["workout_id" => 23, "tag_id" => "10"],
            ["workout_id" => 23, "tag_id" => "22"],
            ["workout_id" => 24, "tag_id" => "9"],
            ["workout_id" => 24, "tag_id" => "14"],
            ["workout_id" => 24, "tag_id" => "15"],
            ["workout_id" => 24, "tag_id" => "20"],
            ["workout_id" => 25, "tag_id" => "9"],
            ["workout_id" => 25, "tag_id" => "14"],
            ["workout_id" => 25, "tag_id" => "15"],
            ["workout_id" => 25, "tag_id" => "20"],
            ["workout_id" => 25, "tag_id" => "21"],
            ["workout_id" => 25, "tag_id" => "23"],
            ["workout_id" => 26, "tag_id" => "9"],
            ["workout_id" => 26, "tag_id" => "14"],
            ["workout_id" => 26, "tag_id" => "20"],
            ["workout_id" => 27, "tag_id" => "9"],
            ["workout_id" => 27, "tag_id" => "14"],
            ["workout_id" => 27, "tag_id" => "15"],
            ["workout_id" => 27, "tag_id" => "22"],
            ["workout_id" => 28, "tag_id" => "10"],
            ["workout_id" => 28, "tag_id" => "14"],
            ["workout_id" => 28, "tag_id" => "15"],
            ["workout_id" => 28, "tag_id" => "23"],
            ["workout_id" => 29, "tag_id" => "10"],
            ["workout_id" => 29, "tag_id" => "15"],
            ["workout_id" => 29, "tag_id" => "22"],
            ["workout_id" => 29, "tag_id" => "21"],
            ["workout_id" => 30, "tag_id" => "10"],
            ["workout_id" => 30, "tag_id" => "14"],
            ["workout_id" => 30, "tag_id" => "15"],
            ["workout_id" => 30, "tag_id" => "23"],
            ["workout_id" => 30, "tag_id" => "21"],
            ["workout_id" => 30, "tag_id" => "22"],
            ["workout_id" => 30, "tag_id" => "20"],
            ["workout_id" => 31, "tag_id" => "17"],
            ["workout_id" => 31, "tag_id" => "9"],
            ["workout_id" => 31, "tag_id" => "10"],
            ["workout_id" => 31, "tag_id" => "11"],
            ["workout_id" => 31, "tag_id" => "12"],
            ["workout_id" => 31, "tag_id" => "22"],
            ["workout_id" => 31, "tag_id" => "23"],
            ["workout_id" => 32, "tag_id" => "17"],
            ["workout_id" => 32, "tag_id" => "11"],
            ["workout_id" => 32, "tag_id" => "12"],
            ["workout_id" => 32, "tag_id" => "20"],
            ["workout_id" => 32, "tag_id" => "21"],
            ["workout_id" => 33, "tag_id" => "17"],
            ["workout_id" => 33, "tag_id" => "9"],
            ["workout_id" => 33, "tag_id" => "10"],
            ["workout_id" => 33, "tag_id" => "11"],
            ["workout_id" => 33, "tag_id" => "12"],
            ["workout_id" => 33, "tag_id" => "20"],
            ["workout_id" => 34, "tag_id" => "17"],
            ["workout_id" => 34, "tag_id" => "9"],
            ["workout_id" => 34, "tag_id" => "20"],
            ["workout_id" => 34, "tag_id" => "22"],
            ["workout_id" => 35, "tag_id" => "17"],
            ["workout_id" => 35, "tag_id" => "9"],
            ["workout_id" => 35, "tag_id" => "11"],
            ["workout_id" => 35, "tag_id" => "22"],
            ["workout_id" => 35, "tag_id" => "20"],
            ["workout_id" => 35, "tag_id" => "21"],
            ["workout_id" => 36, "tag_id" => "18"],
            ["workout_id" => 36, "tag_id" => "12"],
            ["workout_id" => 36, "tag_id" => "15"],
            ["workout_id" => 36, "tag_id" => "14"],
            ["workout_id" => 36, "tag_id" => "22"],
            ["workout_id" => 36, "tag_id" => "23"],
            ["workout_id" => 37, "tag_id" => "18"],
            ["workout_id" => 37, "tag_id" => "9"],
            ["workout_id" => 37, "tag_id" => "20"],
            ["workout_id" => 38, "tag_id" => "18"],
            ["workout_id" => 38, "tag_id" => "10"],
            ["workout_id" => 38, "tag_id" => "11"],
            ["workout_id" => 38, "tag_id" => "20"],
            ["workout_id" => 38, "tag_id" => "21"],
            ["workout_id" => 38, "tag_id" => "22"],
            ["workout_id" => 39, "tag_id" => "18"],
            ["workout_id" => 39, "tag_id" => "15"],
            ["workout_id" => 39, "tag_id" => "22"],
            ["workout_id" => 39, "tag_id" => "21"],
            ["workout_id" => 39, "tag_id" => "20"],
            ["workout_id" => 39, "tag_id" => "10"],
            ["workout_id" => 39, "tag_id" => "11"],
            ["workout_id" => 40, "tag_id" => "18"]
        ];
        DB::table('tag_workout')->insert($workout_tags);
    }
}
